In [1]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data 

nnfs.init()

# Initialize the layer
class Dense_Layer:
    def __init__(self, n_inputs, n_neurons):
#         Initialize weights and biases
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases
        
class Rectified_Linear_Fxn:
#     forward  method for rectified linear activation function
        def forward(self, inputs):
            self.output = np.maximum(0, inputs)
            
# Softmax activation function class            
class Softmax_Activation:
    def forward(self, inputs):
#         softmax implementation
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities
    
# Calculating loss    
class Loss:
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss
    
class Loss_Categorical_Class_Entropy(Loss):
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)
        
#         Handling one hot encoded or scalar values
        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples), y_true]
        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped * y_true, axis=1)
        
        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods
        
X, y = spiral_data(samples=100, classes=3)

# create layer and ReLU objects
dense1 = Dense_Layer(2,3)
activation1 = Rectified_Linear_Fxn()

# Create layer and softmax objects
dense2 = Dense_Layer(3,3)
activation2 = Softmax_Activation()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

loss_function = Loss_Categorical_Class_Entropy()
loss = loss_function.calculate(activation2.output, y)
loss

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]


1.098445